name: Deploy to S3

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API: ${{ secrets.REACT_APP_API }}
    steps:
      - uses: actions/checkout@v2
      - run: echo $REACT_APP_API
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build React App
        run: npm install && npm run build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync /home/runner/work/star-wars-apollo-graphql-client/star-wars-apollo-graphql-client/build/ s3://star-wars-apollo-graphql-client/ --delete